server:
  port: 8002
spring:
    datasource:
      username: root
      password:
      url: jdbc:mysql://127.0.0.1:3306/ssmblog?useUnicode=true&characterEncoding=utf8
      sql-script-encoding: UTF-8
      driverClassName: com.mysql.jdbc.Driver
mybatis:
    type-aliases-package: com.we.weblog.mapping
    config-location: classpath:mybatis-config.xml
    #配置类型别名称